//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_INFO
    {
        public int ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MESSAGE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string CONTACT_PURPOSE { get; set; }
        public string EMAIL_ADDRESS { get; set; }
    }
}
